spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/government_id_db
    username: myuser
    password: mypassword

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
