spring:
  application:
    name: government-id-validation-service
  config:
    import: optional:classpath:config/platform-defaults.yml,optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids: true
server:
  port: ${PORT:8087}
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
